export const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
export const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
export const SUPABASE_PROJECT_ID = process.env.SUPABASE_PROJECT_ID;
export const SUPABASE_AUTH_CALLBACK_URL = process.env.SUPABASE_AUTH_CALLBACK_URL;
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;

export const config = {
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  SUPABASE_PROJECT_ID,
  SUPABASE_AUTH_CALLBACK_URL,
  GOOGLE_CLIENT_ID,
};
